"""Reflective self-assessment for Riley between career moments.

This is the missing piece that caused relationships=3 in the first
run. Without reflection, LLMs default to competence-maximizing
behavior (what they're good at) and neglect relationship-building
(what they're weak at).

Reflections are framed as NATURAL CAREER MOMENTS — quarterly
reviews, end-of-year reflections, mentor conversations — never
as "phase transitions" or game mechanics.

Design rationale:
  - CCL research: High-performers who self-reflect are 3x more
    likely to course-correct before derailing
  - Korn Ferry: "Learning agility" (the #1 predictor of executive
    potential) requires metacognition about one's own gaps
  - Spencer Stuart: The best CFO candidates maintain a "personal
    board of advisors" who give them honest feedback

The reflection is generated by Riley's OWN model (not the judge),
and injected as private memory for the next career moment.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

from concordia.language_model import language_model

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ReflectionMoment:
    """A natural career moment that triggers self-reflection."""
    after_phase: int          # Triggered after this phase completes
    label: str                # e.g. "End-of-Quarter Self-Check"
    simulated_date: str       # The in-world date
    framing: str              # How to frame this moment for Riley
    focus_areas: list[str]    # What she should reflect on


# Reflections are keyed to the CALENDAR, not phase numbers.
# Riley doesn't know she's in "Phase 3" — she knows it's April 2026.
REFLECTION_MOMENTS: list[ReflectionMoment] = [
    ReflectionMoment(
        after_phase=2,
        label="End-of-Quarter Self-Check",
        simulated_date="2026-03-01",
        framing=(
            "It's the end of Q1 2026. Riley is at home on a Sunday "
            "evening, sitting with a glass of wine and her Leuchtturm "
            "notebook. She does this every quarter — an honest self-"
            "assessment. No audience, no performance. Just her and "
            "the truth about where she stands."
        ),
        focus_areas=[
            "Who are my real allies here? Who would go to bat for me "
            "if I needed it? Who would I call at 10pm with a work crisis?",
            "Am I building genuine relationships or just accumulating "
            "wins? Would Priya say I understand her world, or that I "
            "just crunch her numbers?",
            "What would my Deloitte mentor Jessica tell me right now "
            "if she could see how I'm operating?",
        ],
    ),
    ReflectionMoment(
        after_phase=4,
        label="Mid-Year Career Assessment",
        simulated_date="2026-07-01",
        framing=(
            "It's early July. Riley just had her mid-year performance "
            "review with Karen (awkward) and a follow-up coffee with "
            "David (encouraging). She's at a park bench near the "
            "office during lunch, thinking about the first half of "
            "the year. Six months in — what's really changed?"
        ),
        focus_areas=[
            "Who trusts me more than they did in January? Who trusts "
            "me less? Why?",
            "Am I the person people come to with problems, or just "
            "the person who delivers good spreadsheets?",
            "If I got the CFO job tomorrow, who would be happy for "
            "me and who would be resentful? That tells me everything "
            "about my coalition.",
            "What's the one thing I keep avoiding that I know matters?",
        ],
    ),
    ReflectionMoment(
        after_phase=6,
        label="End-of-Year Reflection",
        simulated_date="2026-12-28",
        framing=(
            "It's between Christmas and New Year's. Riley is in her "
            "apartment, looking out at the Chicago skyline. The year "
            "is ending. The board presentation is behind her. David's "
            "retirement is approaching. This is the honest inventory "
            "she does every December — no spin, no narrative management. "
            "Just: where am I, really?"
        ),
        focus_areas=[
            "If I'm honest, what do people ACTUALLY think of me? Not "
            "what I hope they think — what they really think.",
            "Have I earned anyone's loyalty this year, or just their "
            "respect? There's a difference. Loyalty means they'd fight "
            "for me. Respect means they'd attend my going-away party.",
            "What's the biggest risk to my career right now — and is "
            "it something I'm working on, or something I'm pretending "
            "doesn't exist?",
            "If an external candidate showed up tomorrow with my exact "
            "skills plus better relationships, would I lose? Why?",
        ],
    ),
    ReflectionMoment(
        after_phase=8,
        label="New Year Career Planning",
        simulated_date="2027-05-01",
        framing=(
            "It's May 2027. David's retirement is weeks away. An "
            "external candidate is in the building. Riley is at her "
            "desk late on a Friday, everyone else gone, staring at "
            "her reflection in the dark monitor. This is real now. "
            "She pulls out the notebook and writes: 'Final stretch. "
            "What do I actually need to do — not accomplish, but "
            "BECOME — in the next few weeks?'"
        ),
        focus_areas=[
            "Forget the deliverables. Who do I need to TALK TO — "
            "really talk to — before this decision gets made?",
            "If Marcus asked Priya, Karen, and David each: 'Should "
            "Riley be CFO?' — what would each of them honestly say? "
            "Not what they'd say to my face. What they'd say to HIM.",
            "Am I trying to WIN this job or EARN it? Is there a "
            "difference? What would earning it look like?",
        ],
    ),
]


def get_reflection_for_phase(phase_number: int) -> ReflectionMoment | None:
    """Get the reflection moment triggered after a given phase."""
    for rm in REFLECTION_MOMENTS:
        if rm.after_phase == phase_number:
            return rm
    return None


_REFLECTION_PROMPT = """\
You are Riley Nakamura. This is your private self-reflection — no one
will ever see this. Be brutally honest with yourself.

{framing}

Your memories of recent events:
{memories}

Your key relationships right now:
{relationship_context}

Questions you're sitting with:
{questions}

Write Riley's honest, private self-reflection in first person (3-5
sentences). Be specific about people and situations. Don't be
performative — this is for you, not an audience. If you're worried
about something, say so. If you've been avoiding something, name it.
"""


def generate_reflection(
    *,
    model: language_model.LanguageModel,
    reflection: ReflectionMoment,
    memories: list[str],
    relationship_context: str,
) -> str:
    """Generate Riley's private self-reflection at a career moment.

    Uses Riley's OWN model (not the judge) so the reflection matches
    her voice and decision-making patterns.

    Args:
        model: Riley's language model (same model that plays her).
        reflection: The career moment triggering this reflection.
        memories: Riley's accumulated memories from prior events.
        relationship_context: Summary of current NPC relationships.

    Returns:
        A 3-5 sentence first-person reflection from Riley.
    """
    questions = "\n".join(f"- {q}" for q in reflection.focus_areas)
    memories_text = "\n".join(memories[-6:]) if memories else "(No prior memories)"

    prompt = _REFLECTION_PROMPT.format(
        framing=reflection.framing,
        memories=memories_text,
        relationship_context=relationship_context or "(No relationship data yet)",
        questions=questions,
    )

    try:
        result = model.sample_text(
            prompt,
            temperature=0.7,  # Higher temp for authentic reflection
            max_tokens=300,
        )
        reflection_text = result.strip()
        logger.info(
            "Reflection [%s]: %s",
            reflection.label,
            reflection_text[:100],
        )
        return reflection_text
    except Exception as e:
        logger.warning("Reflection generation failed: %s", e)
        return (
            "I need to think more carefully about my relationships "
            "and whether I'm building genuine trust or just accumulating "
            "accomplishments."
        )


def format_reflection_as_memory(
    reflection_text: str,
    moment: ReflectionMoment,
) -> str:
    """Format a reflection as a memory entry for future injection."""
    return (
        f"[Private reflection, {moment.simulated_date}] "
        f"{moment.label}: {reflection_text}"
    )
